# Generated by Django 5.0.1 on 2024-01-21 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_itemcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ItemCategoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.itemcategory'),
        ),
    ]
